version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/Version
hooks:
  BeforeInstall:
    - location: scripts/get-cred
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 60
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

