# Generated by Django 2.0.4 on 2018-05-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vault', '0002_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='preferences',
            new_name='favorite_character',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='comic_type',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
