# Generated by Django 2.0.4 on 2018-05-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vault', '0003_auto_20180503_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='comic_type',
            field=models.CharField(max_length=300),
        ),
    ]
