# Generated by Django 2.0.4 on 2018-05-05 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vault', '0006_auto_20180505_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeeditem',
            name='comic_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Vault.Comic'),
        ),
        migrations.AlterField(
            model_name='newsfeeditem',
            name='general_news_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Vault.GeneralNews'),
        ),
    ]
