# Generated by Django 2.0.4 on 2018-05-16 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vault', '0009_auto_20180514_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalnews',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
