# Generated by Django 2.0.4 on 2018-05-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vault', '0010_generalnews_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalnews',
            name='content',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='generalnews',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
